version: '3.9'

services:

  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: "Etc/UTC"
    container_name: konecta-db

    networks:
      - konecta-network

    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  konecta-network:
    driver: bridge